# Generated by Django 5.1.4 on 2024-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_uploaded_size', models.BigIntegerField(default=0)),
                ('media_folder_size', models.BigIntegerField(default=0)),
            ],
        ),
    ]
