# Generated by Django 5.1.4 on 2024-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0005_rename_db_size_storagestats_total_dedup_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagestats',
            old_name='total_dedup_size',
            new_name='total_hash_size',
        ),
        migrations.AddField(
            model_name='storagestats',
            name='total_unique_data_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
