# Generated by Django 5.1.4 on 2024-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0007_hash_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
